#!/bin/bash

DATABASE=$1
DUMP_DIR=$2

echo "$(date) | Dropping Tables"
mysql-drop-tables ${MYSQL_USERNAME} ${MYSQL_PASSWORD} ${MYSQL_HOSTNAME} ${DATABASE}

echo "$(date) | Importing Tables"
find . -name "${DUMP_DIR}/*.sql.gz"| xargs database-import-table ${DATABASE}
