#!/bin/bash

DATABASE=$1
DUMP_DIR=$2

# work out the number of cpus
MAX_CONCURRENT=4
if command -v "nproc" &> /dev/null; then
  MAX_CONCURRENT=$(nproc)
elif command -v "sysctl" &> /dev/null; then
  MAX_CONCURRENT=$(sysctl -n hw.ncpu)
fi

mysql-drop-tables ${MYSQL_USERNAME} ${MYSQL_PASSWORD} ${MYSQL_HOSTNAME} ${DATABASE}

# define the worker function
import_sql() {
  local sqlfile="$1"
  echo "Starting to import: $sqlfile"
  start=$(date +%s)
  MYSQL_PWD="${MYSQL_PASSWORD}" mysql --user=${MYSQL_USERNAME} --host=${MYSQL_HOSTNAME} ${DATABASE} < $sqlfile
  end=$(date +%s)
  echo "Finished importing $sqlfile in: $(($end-$start)) seconds"
}
export -f import_sql
export DATABASE
export MYSQL_HOSTNAME
export MYSQL_USERNAME
export MYSQL_PASSWORD

find "$DUMP_DIR" -type f -name '*.sql' -print0 \
  | xargs -0 -n1 -P"$MAX_CONCURRENT" bash -c 'import_sql "$@"' _
