#!/bin/bash

DATABASE=$1
DUMP_DIR=$2
DUMP_FILE=$3

mysql-drop-tables ${MYSQL_USERNAME} ${MYSQL_PASSWORD} ${MYSQL_HOSTNAME} ${DATABASE}

echo "Importing ${DUMP_DIR}/${DUMP_FILE} ..."
start=$(date +%s)
MYSQL_PWD="${MYSQL_PASSWORD}" mysql --user=${MYSQL_USERNAME} --host=${MYSQL_HOSTNAME} ${DATABASE} < ${DUMP_DIR}/${DUMP_FILE}
end=$(date +%s)
echo "Finished importing $i in: $(($end-$start)) seconds"