#!/bin/bash

NAME=$1
FILE=$2

echo "$(date) | Creating database ${NAME}..."
mysql -uroot -proot -e "CREATE DATABASE ${NAME}"

echo "$(date) | Importing database ${NAME} from ${FILE} ..."
mysql -uroot -proot -D ${NAME} < ${FILE}

echo "$(date) | Analyzing databases..."
mysqlcheck -uroot -proot --auto-repair --analyze ${NAME}
