#!/bin/bash

USER=$1
PASS=$2
NAME=$3
FILE=$4

mysql-start &
wait-port 127.0.0.1 3306 100000

#https://dev.mysql.com/doc/refman/8.4/en/innodb-redo-log.html#innodb-disable-redo-logging
mysql -uroot -proot -e "ALTER INSTANCE DISABLE INNODB REDO_LOG;"

database-create $NAME $FILE

mysql -uroot -proot -e "ALTER INSTANCE ENABLE INNODB REDO_LOG;"

user-create $NAME $USER $PASS

mysql-stop
